### ISSUE TITLE
Nice Project

### ISSUE THREAD

**Issue by ethanfrey** [thyeem/monotree#3]
Hi, I was looking for a simple merklized database in Rust to experiment with and this came up. It looks nice and simple and fast. 

I ran some benchmarks locally and read the examples, and I like the design in general. I am not sure if this is being maintained much now, but a few questions on proper usage:

* It exposes batches of all inserts or all removes or all gets. What about a batch of mixed inserts and removed? Is that just limited due to keeping the API simple? Or is there a reason it would be tricky to add?
* This stores key_hash -> value_hash with merkle proof potential, which is nice an small. To use as a real storage, I would need a sibling DB to store the raw key->value mapping (unmerklized) and keep this just for proofs, correct?
* RocksDB offers checkpoints, so I could provide read-only access to one version (for consistent long-reads/admin) while continuing to write. This is not exposed, but I assume this is mainly an issue of API clarity?

I don't want to ask you to implement these, but I would be interested in hearing if your thoughts on them and if they could be added without huge complexity overhead.

One issue there is keeping 2 databases in sync if I cannot commit atomically over them both. I could imagine sharing one eg. RocksDB under the hood, with all data stored with eg. `0` prefix and all data from MonoTree with `1`. Then building a batch that contains all data updates and all MonoTree updates, so I can get the data and the proofs together in an atomic commit. This would require:
  * Prepending a prefix to writes, stripping from reads
  * Passing in a DB rather than creating it internally - for every call
  * (Most challenging) Relying on "someone else" to manage the batches and access

Apart from the API challenges, do you think something like that would be feasible? 

Thank you for your time reading this. And let me know if I can support the project somehow.

**Comment by thyeem** [comment]
Sorry for deadly late reply and for not being maintained much lately while you left lots of helpful comments!
It was long ago and I think you already get some your own answers, but I feel like I must leave answers.


1. **A batch of mixed insert() and remove()**:
Honestly, I've never thought about what you pointed out. Back then, I came up with only those pairs of functions the following: `get()` and `gets()`, `insert()` and `inserts()`, and `remove()` and `removes()`.
There were no special reason at all, except for keeping it simple. It would be more useful and faster if the monotree also has a batch of mixed `insert()` and `remove()` like RocksDB!


2. **To use as a real storage**:
You observed well that `monotree` stores `key_hash` -> `value_hash`. But I don't think you need a sibling DB to store `raw_key` -> `value` map if I get your words correctly. You can just use the same DB: `value_hash == raw_key`. 

No distinction between node hash and leaf hash, thus no need to check if a node is a leaf.

As you know, the `monotree` dynamically changes key prefixes for each input like a Patricia tree as part of the optimization.
the monotree has no such thing like `is_leaf()`. Leaves are automatically determined as the result of key-path-compression.
If you keep reading a tree path (fragments of a `key_hash`) you automatically get the leaf, the very bottom one.
(See: https://github.com/thyeem/monotree/blob/master/src/tree.rs#L119)


Probably you might simply want to have 2 DBs in sync in specific situation (like read-only access as you said, or sharding purpose). It seems that you've been thinking a lot about operating two databases in sync. I'm not enough to talk about it.

One thing I can say for sure is that the monotree is designed for the `stateroot` of the blockchain, and will work enough to handle block speeds.

It would be better if this could be develepoed further in many ways. Thanks for sharing your thoughts and helpful comments.
I'll invite you as a collaborator of this project if you'd like to join us.

**Comment by ethanfrey** [comment]
Thanks for the reply in the end. I went with with https://github.com/nomic-io/merk which, while fast, doesn't seem nearly as fast as yours (compare RocksDB benchmarks).

> It would be better if this could be develepoed further in many ways. Thanks for sharing your thoughts and helpful comments. I'll invite you as a collaborator of this project if you'd like to join us.

It might be interesting to dig in, but it seems the project is inactive? Last commit about 18 months ago. Or am I wrong?

**Comment by thyeem** [comment]
You're right. It has been inactive for a long time and I've bumped up dependencies just now. 

There's still something left for monotree to be a completely parameterized SMT.
Back then I had an idea, but I've been busy with other things (zero-knowledge proof).

**Comment by thyeem** [comment]
The goal of this project was .. simply to provide an non-verbose and optimized SMT at an abstract level rather than an application level.
In the way of no-frills, easy-to-use and easy-to-scale...

For now, I feel it's the right time to experiment with this project at the application level in the way somebody likes. 
I've invited you to this project.
